version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: last-apply-db
    environment:
      POSTGRES_DB: lastapply
      POSTGRES_USER: lastapply_user
      POSTGRES_PASSWORD: lastapply_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: last-apply-minio
    environment:
      MINIO_ROOT_USER: lastapply
      MINIO_ROOT_PASSWORD: lastapply123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: